name: Java CI with Maven
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  pipeline:
    uses: eherediam/central-workflow/javaMaven@main
    with:
      JAVA_VERSION: '17'
      DISTRIBUTION: 'temurin'
      CACHE: 'maven'
    secrets: inherit  