name: Java CI with Maven
on:
  workflow_dispatch:

jobs:
  pipeline:
    uses: eherediam/central-workflow/.github/workflows/javaMavenWrapper.yml@main
    with:
      JAVA_VERSION: '8'
      DISTRIBUTION: 'temurin'
      CACHE: 'maven'
    secrets: inherit  