name: Java CI with Maven
on:
  push:
    branches: [ "main" , "master" ]

jobs:
  pipeline:
    uses: eherediam/central-workflow/.github/workflows/maven.yml@main
    with:
      JAVA_VERSION: '17'
      DISTRIBUTION: 'temurin'
      CACHE: 'maven'
    secrets: inherit  